<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Momo" name="org.example.testRunner.runners" tests="19" failures="2" timestamp="2022-09-19T22:59:07 EET" time="213.559" errors="1">
  <testcase name="runScenario" time="7.220" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="15.081" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="7.915" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="9.812" classname="org.example.testRunner.runners">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at org.example.pages.P03_homePage.rssNewTab(P03_homePage.java:195)
at org.example.stepDefs.D07_followUsStepDef.rssNewtab(D07_followUsStepDef.java:34)
at ✽.rss link is opened in new tab(file:///C:/Users/engmo/IdeaProjects/E-commerceAppAutomationTesting/src/main/resources/features/F07_followUs.feature:13)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="8.289" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="8.513" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.262" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="19.774" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="10.887" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.403" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.411" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="6.370" classname="org.example.testRunner.runners">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.pages.P03_homePage.firstProductUrl(P03_homePage.java:141)
at org.example.stepDefs.D06_homeSlidersStepDef.firstProductUrl(D06_homeSlidersStepDef.java:21)
at ✽.user redirected to first product page(file:///C:/Users/engmo/IdeaProjects/E-commerceAppAutomationTesting/src/main/resources/features/F06_homeSliders.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="6.426" classname="org.example.testRunner.runners">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.pages.P03_homePage.secondProductUrl(P03_homePage.java:156)
at org.example.stepDefs.D06_homeSlidersStepDef.secondProductUrl(D06_homeSlidersStepDef.java:34)
at ✽.user redirected to second product page(file:///C:/Users/engmo/IdeaProjects/E-commerceAppAutomationTesting/src/main/resources/features/F06_homeSliders.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="7.149" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.488" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="8.757" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="28.278" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="12.134" classname="org.example.testRunner.runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.390" classname="org.example.testRunner.runners"/>
  <system-out/>
</testsuite> <!-- org.example.testRunner.runners -->
